import { InventoryItem } from "./types";

export interface OfficialLguItem {
  article: string;
  description: string;
  propertyNumber: string;
  unitOfMeasure: string;
  unitValue: number;
  qtyPropertyCard: number;
  qtyPhysicalCount: number;
  category: string;
  office: string;
  acquisitionDate: string;
  isFixed: boolean;
  condition: "Good" | "Brand New" | "Fair" | "Damaged";
  status: "AVAILABLE";
  remarks: string;
}

export const OFFICIAL_LGU_INVENTORY: OfficialLguItem[] = [
  {
    article: "Motorcycle (HONDA XR)",
    description: "Official fixed master data item from LGU inventory sheet (PAR).",
    propertyNumber: "LGU-MDRRMO-PAR-2015-XR",
    unitOfMeasure: "Unit",
    unitValue: 80000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Transportation Equipment",
    office: "MDRRMO",
    acquisitionDate: "10/6/2015",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "VHF Repeater set up w/ accessories",
    description: "VHF Repeater Set with accessories (Master Data).",
    propertyNumber: "LGU-MDRRMO-PAR-2016-VHF",
    unitOfMeasure: "Set",
    unitValue: 68000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Communication Equipment",
    office: "MDRRMO",
    acquisitionDate: "8/19/2016",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Rescue Vehicle",
    description: "MDRRMO emergency rescue vehicle (Master Data).",
    propertyNumber: "LGU-MDRRMO-PAR-2016-RESV",
    unitOfMeasure: "Unit",
    unitValue: 1295000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Transportation Equipment",
    office: "MDRRMO",
    acquisitionDate: "9/28/2016",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Vehicle",
    description: "LGU standard utility vehicle (Master Data).",
    propertyNumber: "LGU-MDRRMO-PAR-2019-VEH",
    unitOfMeasure: "Unit",
    unitValue: 1099000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Transportation Equipment",
    office: "MDRRMO",
    acquisitionDate: "7/26/2019",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Fire Extinguisher",
    description: "Office and rescue fire extinguisher unit (Master Data).",
    propertyNumber: "LGU-MDRRMO-PAR-2017-FE",
    unitOfMeasure: "Unit",
    unitValue: 88750.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Safety Equipment",
    office: "MDRRMO",
    acquisitionDate: "6/6/2017",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Serie",
    description: "Specialized rescue or communication series system.",
    propertyNumber: "LGU-MDRRMO-PAR-2017-SERIE",
    unitOfMeasure: "Unit",
    unitValue: 265000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Other Assets",
    office: "MDRRMO",
    acquisitionDate: "12/20/2017",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Water Rescue Equipment",
    description: "Water safety and marine rescue equipment (Master Data).",
    propertyNumber: "LGU-MDRRMO-PAR-2018-WREQ",
    unitOfMeasure: "Unit",
    unitValue: 82500.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Safety Equipment",
    office: "MDRRMO",
    acquisitionDate: "June 2018",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Training Kit",
    description: "LDRRM training kit and pedagogical materials.",
    propertyNumber: "LGU-MDRRMO-PAR-2016-TRKT",
    unitOfMeasure: "Unit",
    unitValue: 295000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Other Assets",
    office: "MDRRMO",
    acquisitionDate: "10/28/2016",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Motorcycle (YAMAHA YTX)",
    description: "Yamaha YTX service motorcycle units.",
    propertyNumber: "LGU-MDRRMO-PAR-2018-YTX",
    unitOfMeasure: "Units",
    unitValue: 102200.00,
    qtyPropertyCard: 2,
    qtyPhysicalCount: 2,
    category: "Transportation Equipment",
    office: "MDRRMO",
    acquisitionDate: "Oct. 2018",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Vehicle",
    description: "Transport service vehicle for emergency response.",
    propertyNumber: "LGU-MDRRMO-PAR-2018-VEH2",
    unitOfMeasure: "Unit",
    unitValue: 1750000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Transportation Equipment",
    office: "MDRRMO",
    acquisitionDate: "Dec. 2018",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Diving equipment",
    description: "Complete aquatic diving equipment set.",
    propertyNumber: "LGU-MDRRMO-PAR-2020-DIVE",
    unitOfMeasure: "Units",
    unitValue: 110600.00,
    qtyPropertyCard: 2,
    qtyPhysicalCount: 2,
    category: "Safety Equipment",
    office: "MDRRMO",
    acquisitionDate: "01/23/2020",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Chainsaw",
    description: "Industrial chainsaw for debris clearing operations.",
    propertyNumber: "LGU-MDRRMO-PAR-2020-CSAW",
    unitOfMeasure: "Unit",
    unitValue: 72600.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Other Assets",
    office: "MDRRMO",
    acquisitionDate: "07/07/2020",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Transport Vehicle",
    description: "Standard general-purpose transport vehicle.",
    propertyNumber: "LGU-MDRRMO-PAR-2021-TRNS",
    unitOfMeasure: "Unit",
    unitValue: 0.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Transportation Equipment",
    office: "MDRRMO",
    acquisitionDate: "10/07/2021",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Digital SLR Camera Kit (EOS Rebel T6i with EF-S 18-55mm & EF 75-300mm Lens)",
    description: "Digital DSLR photography kit for emergency documentation.",
    propertyNumber: "LGU-MDRRMO-PAR-2021-CAM",
    unitOfMeasure: "Set",
    unitValue: 50000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "ICT Equipment",
    office: "MDRRMO",
    acquisitionDate: "2021",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Laptop",
    description: "Standard processing computer (Master Data).",
    propertyNumber: "LGU-MDRRMO-PAR-2021-LAP1",
    unitOfMeasure: "Unit",
    unitValue: 50000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "ICT Equipment",
    office: "MDRRMO",
    acquisitionDate: "2021",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Coaster",
    description: "Heavy mass-transport coaster vehicle.",
    propertyNumber: "LGU-MDRRMO-PAR-2012-COAS",
    unitOfMeasure: "units",
    unitValue: 799000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Transportation Equipment",
    office: "MDRRMO",
    acquisitionDate: "11/30/2012",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Antenna/Receiver",
    description: "RF antenna and receiver kit.",
    propertyNumber: "LGU-MDRRMO-PAR-2022-ANT",
    unitOfMeasure: "unit",
    unitValue: 99000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Communication Equipment",
    office: "MDRRMO",
    acquisitionDate: "Sept. 2022",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Diesel Generator Set",
    description: "Heavy emergency backup diesel generator.",
    propertyNumber: "LGU-MDRRMO-PAR-GENSET",
    unitOfMeasure: "unit",
    unitValue: 372060.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Other Assets",
    office: "MDRRMO",
    acquisitionDate: "",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Rescue Manual Spreader Cutter Hydraulic Combination Tool",
    description: "Hydraulic spreader and cutter combi tool set.",
    propertyNumber: "LGU-MDRRMO-PAR-HYD",
    unitOfMeasure: "unit",
    unitValue: 748500.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Safety Equipment",
    office: "MDRRMO",
    acquisitionDate: "",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Laptop",
    description: "General support workstation laptop.",
    propertyNumber: "LGU-MDRRMO-PAR-LAP2",
    unitOfMeasure: "unit",
    unitValue: 61320.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "ICT Equipment",
    office: "MDRRMO",
    acquisitionDate: "",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Emergency Response Vehicle",
    description: "High capacity command response vehicle.",
    propertyNumber: "LGU-MDRRMO-PAR-ERV",
    unitOfMeasure: "unit",
    unitValue: 1971200.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Transportation Equipment",
    office: "MDRRMO",
    acquisitionDate: "",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Mass Transportation Vehicle / Heavy Equipment",
    description: "MDRRMO Mass Transport vehicle or high weight machinery.",
    propertyNumber: "LGU-MDRRMO-PAR-HVYE",
    unitOfMeasure: "unit",
    unitValue: 2090000.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Transportation Equipment",
    office: "MDRRMO",
    acquisitionDate: "",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (PAR)"
  },
  {
    article: "Fire Extinguisher",
    description: "Standard issue portable fire extinguisher (ICS).",
    propertyNumber: "LGU-MDRRMO-ICS-FE",
    unitOfMeasure: "Units",
    unitValue: 0.00,
    qtyPropertyCard: 6,
    qtyPhysicalCount: 6,
    category: "Safety Equipment",
    office: "MDRRMO",
    acquisitionDate: "",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (ICS Table)"
  },
  {
    article: "CPR - Manikin (Half Body)",
    description: "Standard half body medical CPR resuscitation training dummy.",
    propertyNumber: "LGU-MDRRMO-ICS-CPR",
    unitOfMeasure: "Unit",
    unitValue: 0.00,
    qtyPropertyCard: 1,
    qtyPhysicalCount: 1,
    category: "Medical Equipment",
    office: "MDRRMO",
    acquisitionDate: "",
    isFixed: true,
    condition: "Good",
    status: "AVAILABLE",
    remarks: "Official Fixed Asset Master Data (ICS Table)"
  }
];
